version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - APP_URL=${APP_URL:-http://localhost:3000}
      - innovistapos_AWS_ACCOUNT_ID=${innovistapos_AWS_ACCOUNT_ID:-041436772015}
      - innovistapos_AWS_REGION=${innovistapos_AWS_REGION:-us-east-1}
      - innovistapos_AWS_RESOURCE_ARN=${innovistapos_AWS_RESOURCE_ARN:-arn:aws:rds:us-east-1:041436772015:cluster:innovistaposdbaws}
      - innovistapos_AWS_ROLE_ARN=${innovistapos_AWS_ROLE_ARN:-arn:aws:iam::041436772015:role/Vercel/access-innovistaposdbaws}
      - innovistapos_PGDATABASE=${innovistapos_PGDATABASE:-postgres}
      - innovistapos_PGHOST=${innovistapos_PGHOST:-innovistaposdbaws.cluster-cct88acowp78.us-east-1.rds.amazonaws.com}
      - innovistapos_PGPORT=${innovistapos_PGPORT:-5432}
      - innovistapos_PGSSLMODE=${innovistapos_PGSSLMODE:-require}
      - innovistapos_PGUSER=${innovistapos_PGUSER:-postgres}
      - innovistapos_PGPASSWORD=${innovistapos_PGPASSWORD:-}
    volumes:
      - pos_data:/app/data

volumes:
  pos_data:
